.TH BUILTIN 1 "March 19, 2018" "Version 1.0" "42sh Manual"

.SH NAME
.P
color

.SH SYNOPSIS
.P
color [arg]

.SH DESCRIPTION
.P
The color utility put the color on or off.
if there is no argument or if theargument is "on", the color is put on.
Otherwise, the color is put off.

.SH EXIT STATUS
.P
This utility returns 0 on success and >0 if error occurs.

.SH AUTHOR
.P
Deborah Recourse and Virgile Desvaux
