.TH BUILTIN 1 "January 25, 2018" "Version 1.0" "42sh Manual"

.SH NAME
.P
cd

.SH SYNOPSIS
.P
cd [-LP] [-|<dir>]

.SH DESCRIPTION
.P


.SH OPTIONS
.P
-L
.PP
.P
-P
.PP

.SH EXIT STATUS
.P

.SH EXAMPLE
.P
To return to the directory above the current one:
.PP
$cd ..

.SH AUTHOR
.P
Deborah Recourse and Virgile Desvaux
